import type { Provider, Job, Package, Contract } from './types'

export type { Provider, Job, Package, Contract }

export const mockProvider: Provider = {
  id: 'sarah-captures',
  name: 'Sarah Mensah',
  businessName: 'Sarah Captures',
  email: 'sarah@captures.com',
  phone: '+233541234567',
  serviceCategory: 'Photography',
  bookingUrl: 'app.com/book/sarah-captures',
}

export const mockJobs: Job[] = [
  {
    id: 'job-001',
    clientName: 'Ama Owusu',
    email: 'ama@email.com',
    phone: '+233542222222',
    serviceType: 'Wedding Photography',
    eventDate: 'June 15, 2024',
    location: 'Accra, Ghana',
    packageName: 'Premium Wedding',
    packagePrice: 2500,
    depositAmount: 625,
    depositPaid: true,
    balanceAmount: 1875,
    balancePaid: false,
    contractSigned: true,
    status: 'in-progress',
  },
  {
    id: 'job-002',
    clientName: 'Kwame Asante',
    email: 'kwame@email.com',
    phone: '+233543333333',
    serviceType: 'Corporate Event',
    eventDate: 'May 20, 2024',
    location: 'Kumasi, Ghana',
    packageName: 'Standard Corporate',
    packagePrice: 1200,
    depositAmount: 300,
    depositPaid: true,
    balanceAmount: 900,
    balancePaid: true,
    contractSigned: true,
    status: 'completed',
    completedDate: 'May 21, 2024',
  },
  {
    id: 'job-003',
    clientName: 'Abena Boateng',
    email: 'abena@email.com',
    phone: '+233544444444',
    serviceType: 'Engagement Session',
    eventDate: 'June 8, 2024',
    location: 'Accra, Ghana',
    packageName: 'Engagement Package',
    packagePrice: 800,
    depositAmount: 200,
    depositPaid: false,
    balanceAmount: 600,
    balancePaid: false,
    contractSigned: false,
    status: 'pending',
  },
  {
    id: 'job-004',
    clientName: 'Kofi Mensah',
    email: 'kofi@email.com',
    phone: '+233545555555',
    serviceType: 'Product Photography',
    eventDate: 'May 10, 2024',
    location: 'Tema, Ghana',
    packageName: 'Standard Product',
    packagePrice: 400,
    depositAmount: 100,
    depositPaid: true,
    balanceAmount: 300,
    balancePaid: true,
    contractSigned: true,
    status: 'cancelled',
  },
]

export const mockPackages: Package[] = [
  {
    id: 'pkg-001',
    name: 'Premium Wedding',
    serviceType: 'Wedding Photography',
    description: 'Full-day coverage with album and prints',
    price: 2500,
    depositPercentage: 25,
    inclusions: ['8 hours coverage', '500+ photos', 'Digital album', 'Print package'],
  },
  {
    id: 'pkg-002',
    name: 'Standard Corporate',
    serviceType: 'Corporate Event',
    description: 'Half-day event coverage',
    price: 1200,
    depositPercentage: 25,
    inclusions: ['4 hours coverage', '200+ photos', 'Digital delivery'],
  },
]

export const mockContracts: Contract[] = [
  {
    id: 'contract-001',
    clientName: 'Ama Owusu',
    eventDate: 'June 15, 2024',
    eventLocation: 'Accra, Ghana',
    serviceType: 'Wedding Photography',
    totalPrice: 2500,
    depositAmount: 625,
    status: 'signed',
    content: {
      provider: 'Sarah Captures',
      client: 'Ama Owusu',
      services: 'Full-day wedding photography coverage including 500+ edited photos, digital album, and print package.',
      investment: {
        total: 2500,
        deposit: 625,
        balanceDueDate: 'June 1, 2024',
      },
      terms: 'Client agrees to the terms outlined in this contract. Both parties agree to professional conduct and respect.',
    },
  },
  {
    id: 'contract-002',
    clientName: 'Kwame Asante',
    eventDate: 'May 20, 2024',
    eventLocation: 'Kumasi, Ghana',
    serviceType: 'Corporate Event',
    totalPrice: 1200,
    depositAmount: 300,
    status: 'signed',
    content: {
      provider: 'Sarah Captures',
      client: 'Kwame Asante',
      services: 'Half-day corporate event coverage including 200+ edited photos and digital delivery.',
      investment: {
        total: 1200,
        deposit: 300,
        balanceDueDate: 'May 15, 2024',
      },
      terms: 'Client agrees to the terms outlined in this contract. Both parties agree to professional conduct and respect.',
    },
  },
  {
    id: 'contract-003',
    clientName: 'Abena Boateng',
    eventDate: 'June 8, 2024',
    eventLocation: 'Accra, Ghana',
    serviceType: 'Engagement Session',
    totalPrice: 800,
    depositAmount: 200,
    status: 'pending-signature',
    content: {
      provider: 'Sarah Captures',
      client: 'Abena Boateng',
      services: 'Engagement photography session including 100+ edited photos and digital delivery.',
      investment: {
        total: 800,
        deposit: 200,
        balanceDueDate: 'June 1, 2024',
      },
      terms: 'Client agrees to the terms outlined in this contract. Both parties agree to professional conduct and respect.',
    },
  },
]
